# Generated by Django 4.1.7 on 2023-03-14 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название публикации")),
                ("text", models.TextField(verbose_name="Содержимое публикации")),
                (
                    "date",
                    models.DateField(auto_now=True, verbose_name="Дата публикации"),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("CO", "Комедия"),
                            ("TR", "Трагедия"),
                            ("DR", "Драма"),
                            ("HO", "Ужасы"),
                        ],
                        default="CO",
                        max_length=2,
                    ),
                ),
                (
                    "is_adult_only",
                    models.BooleanField(
                        default=False, verbose_name="Только для взрослых?"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
